### ISSUE TITLE
How can I solve it

### ISSUE THREAD

**Issue by 3hxks** [I2rys/BlazeKai#1]
[root@sk4z12s601sl2mn3 BlazeKai]# node index.js 10 dork.txt 11.txt

internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /root/BlazeKai/node_modules/chalk/source/index.js
require() of ES modules is not supported.
require() of /root/BlazeKai/node_modules/chalk/source/index.js from /root/BlazeKai/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /root/BlazeKai/node_modules/chalk/source/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/BlazeKai/node_modules/chalk/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/BlazeKai/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}
[root@sk4z12s601sl2mn3 BlazeKai]# 

My NodeJS version:
[root@sk4z12s601sl2mn3 BlazeKai]# node -v
v12.22.9

**Comment by I2rys** [comment]
Hello @3hxks, the newest version of chalk is for Typescript only. So just download one of the oldest version of it to fix this problem.
```
npm uninstall chalk && npm i chalk@2.4.2
```
